#!/usr/bin/env bash
# Apply shell configuration. Never overwrites ~/.zshrc; appends a marked block.

configure_shell() {
  log_info "Configuring Zsh, aliases and functions"

  if is_dry_run; then
    log_dry "ensure ~/.zshrc sources ${REPO_ROOT}/shell/zshrc via a marked block"
    log_dry "optionally chsh to zsh for $(id -un)"
    state_append_list "MODULES" "shell"
    return 0
  fi

  mkdir -p "${XDG_CONFIG_HOME}/zsh"
  _write_zsh_env_file

  local block
  block="$(cat <<EOF
# Managed by ubuntu-dotfiles. Safe to remove this block; your other zsh settings stay.
export UBUNTU_DOTFILES_ROOT="${REPO_ROOT}"
if [ -f "\${UBUNTU_DOTFILES_ROOT}/shell/zshrc" ]; then
  . "\${UBUNTU_DOTFILES_ROOT}/shell/zshrc"
fi
EOF
)"
  upsert_marked_block "${HOME}/.zshrc" "${block}"

  # Keep bash usable: add a small pointer so opening a bash terminal still has PATH.
  local bash_block
  bash_block="$(cat <<EOF
# Managed by ubuntu-dotfiles (PATH only; full config lives in zsh).
export PATH="\${HOME}/.local/bin:\${PATH}"
EOF
)"
  upsert_marked_block "${HOME}/.bashrc" "${bash_block}"

  _maybe_change_shell_to_zsh
  state_append_list "MODULES" "shell"
  state_set "ZSHRC_MANAGED" "1"
}

_write_zsh_env_file() {
  local dest="${DOTFILES_CONFIG_DIR}/env.sh"
  local content
  content="$(cat <<EOF
# Generated by ubuntu-dotfiles. Machine-local paths only. No secrets.
export UBUNTU_DOTFILES_ROOT="${REPO_ROOT}"
export NVM_DIR="\${NVM_DIR:-${HOME}/.nvm}"
export PATH="\${HOME}/.local/bin:\${PATH}"
EOF
)"
  write_file "${dest}" "${content}"
}

_maybe_change_shell_to_zsh() {
  local zsh_path
  zsh_path="$(command -v zsh || true)"
  if [[ -z "${zsh_path}" ]]; then
    log_warn "zsh is not on PATH; skip login-shell change"
    return 0
  fi

  local current
  current="$(getent passwd "$(id -un)" | awk -F: '{print $7}')"
  if [[ "${current}" == "${zsh_path}" ]]; then
    log_skip "Login shell is already zsh"
    return 0
  fi

  if ! grep -qx "${zsh_path}" /etc/shells 2>/dev/null; then
    log_warn "${zsh_path} is not listed in /etc/shells; skip chsh"
    return 0
  fi

  log_info "Your login shell is ${current}. Changing it to zsh improves the developer terminal."
  log_info "This does not remove bash. You can switch back with: chsh -s $(command -v bash)"

  if [[ "${ASSUME_YES}" != "1" ]]; then
    if ! confirm "Set zsh as the login shell for $(id -un)?"; then
      log_skip "Login shell left as ${current}"
      return 0
    fi
  fi

  if chsh -s "${zsh_path}"; then
    log_success "Login shell set to ${zsh_path}. Open a new terminal to use it."
    state_set "PREVIOUS_SHELL" "${current}"
  else
    log_warn "chsh failed. Set it later with: chsh -s ${zsh_path}"
  fi
}
