# Full greeting shown when a new terminal opens.
print_info() {
    info title
    info underline

    info "OS" distro
    info "Host" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Resolution" resolution
    info "DE" de
    info "WM" wm
    info "Theme" theme
    info "Icons" icons
    info "Terminal" term
    info "Term Font" term_font
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory
    info "Disk" disk
    info "Battery" battery
    info "Local IP" local_ip
    prin
    info cols
}

ascii_distro="ubuntu"
ascii_bold="on"
colors=(5 7 6 1 8 15)
color_blocks="on"
block_range=(0 15)
block_width=3
block_height=1

kernel_shorthand="on"
distro_shorthand="off"
os_arch="on"
uptime_shorthand="on"
memory_percent="on"
memory_unit="gib"
package_managers="on"
shell_path="off"
shell_version="on"
cpu_brand="on"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="off"
gpu_brand="on"
refresh_rate="on"
gtk_shorthand="off"
bold="on"
underline_enabled="on"
stdout="off"
de_version="on"
local_ip_interface=('auto')
